# action.yml
name: 'LÖVE Build'
author: 'Nathan Hartland <@nhartland>'
description: 'Action for building LÖVE project distributables (Win32/Win64/Mac/love)'
branding:
  icon: 'heart'
  color: 'blue'
inputs:
  app_name:
    description: 'Name of the application to be built'
    default: 'love-build-app'
    required: true
  love_version:
    description: 'Version of LÖVE to be used in building the application'
    default: '11.3'
    required: true
  dependencies:
    description: 'Path to dependencies rockspec in source_dir'
    required: false
  source_dir:
    description: 'Path in the repository to the subdirectory containing `main.lua`. By default the repo root'
    default: ""
    required: true
  result_dir:
    description: 'Directory in the GitHub workspace where the built distributables should be located'
    default: "release"
    required: true
outputs:
  love-filename: 
    description: 'Path (relative to GitHub workspace) of built love file'
  win32-filename: 
    description: 'Path (relative to GitHub workspace) of built win32 application'
  win64-filename: 
    description: 'Path (relative to GitHub workspace) of built win64 application'
  macos-filename: 
    description: 'Path (relative to GitHub workspace) of built macos application'
runs:
  using: 'docker'
  image: 'Dockerfile'
